#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("R19_BW_laczenia_Android.Resource", IsApplication=true)]

namespace R19_BW_laczenia_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int typyPrzedmiotow = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int btnCofnij = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int btnDodaj = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int btnOK = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int btnOpcje = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int btnWroc = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int btnWroc2 = 2131099658;
			
			// aapt resource value: 0x7f06001e
			public const int btnWyswietlBaza = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int btnWyswietlPref = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int btnWyswietlSuf = 2131099679;
			
			// aapt resource value: 0x7f060019
			public const int btnZamknij = 2131099673;
			
			// aapt resource value: 0x7f060010
			public const int btnZapisz = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int itemSelector = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout_gridtableLayout = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int listaOpcji = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int listaPrzedmiotow = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int seatLegendLayout = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int spinnerBaza = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int spinnerPref = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int spinnerSuf = 2131099657;
			
			// aapt resource value: 0x7f06001c
			public const int spinnerTabelaTyp = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int tabela = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int tabelaTekst = 2131099674;
			
			// aapt resource value: 0x7f060015
			public const int textAbev = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int textBaza = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int textImportPrzedm = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int textImportTyp = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int textPref = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int textSuf = 2131099656;
			
			// aapt resource value: 0x7f06001b
			public const int textTyp = 2131099675;
			
			// aapt resource value: 0x7f060014
			public const int textVersion = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int textWynik = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddItem = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AddNewItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LoadItems = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Opcje = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Table = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int WybierzTable = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
	}
}
#pragma warning restore 1591
